db:
  image: mysql/mysql-server
  ports:
    - "3306:3306"
  volumes:
    - ./var/mysql:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=root
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=password

web:
  image: tutum/apache-php
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - ./www:/app

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:mysql
  ports:
    - 8181:80
  volumes:
    - ./var/phpmyadmin:/var/lib/phpmyadmin
  environment:
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=password
