db:
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: database
    MYSQL_PASSWORD: password

apache:
  image: tutum/apache-php
  links:
    - db
  volumes:
    - ./www:/app
  ports:
    - 80:80
  restart: always
  environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_PASSWORD: wordpress

phpmyadmin:
  links:
    - db
  image: phpmyadmin/phpmyadmin
  environment:
          #PMA_ARBITRARY: 1
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          PMA_HOST: db

  ports:
    - 8848:80
